# name: action workflow
# on:
#   schedule:
#     - cron: "5 * * * *"
#   pull_request:
#     types: [close, assigned, opened, reopened] #[push]

# jobs:
#   git-hub-actions:
#     runs-on: ubuntu-latest
#     steps: 
#       # - name: simple javascript actions
#       #   id: hello
#       #   uses: actions/hello-world-javascript-action@v1
#       #   with:
#       #     who-to-greet: hello vishnutheja
#       - name: get the output time
#         run: echo "${{ steps.hello.outputs.time }}"
#   # test-github-actions:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: list files
#   #       run: |
#   #         pwd
#   #         ls -a
#   #         echo $GITHUB_SHA
#   #         echo $GITHUB_REPOSITORY
#   #         echo $GITHUB_WORKSPACE
#   #         echo "${{ github.token }}""

#   #     - name: checkout
#   #       uses: actions/checkout@v1
#   #     - name: list files after checkout
#   #       run: | 
#   #         pwd
#   #         ls -a
#       # - name: simple javascript applicaiton
#       #   id: hello
#       #   uses: actions/hell-world-javascript-action@v1
#       #   with:
#       #     who-to-greet: vishnutheja
name: Action Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: List Files After Checkout
        run: |
          pwd
          ls -a


      - name: Simple Javascript Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: devopshint

      - name: Get the output time
        run: echo "${{ steps.hello.outputs.time }}"