name: shell sample commands

on: [push] #pull

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo "hello vishnutheja"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  
  runs-on-windows-command:
    runs-on: windows-latest
    steps:
      - name: powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash