name: shell sample commands

on: [push] #pull

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
        run: echo "hello vishnutheja"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(plantform.processor())
        shell: python